# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Izt-wv9su6nCl8tGencAl3Pe8ehtLARg
"""

import random

class TicTacToe:
    def __init__(self):
        # 1. The game starts with an empty 3 × 3 board containing nine positions.
        self.board = [[' ' for _ in range(3)] for _ in range(3)]
        # 2. There are two players: the Human Player (X) and the Computer Player (O).
        self.human = 'X'
        self.computer = 'O'

    def display_board(self):
        """Helper function to print the current state of the board."""
        for i, row in enumerate(self.board):
            print(f" {row[0]} | {row[1]} | {row[2]} ")
            if i < 2:
                print("-----------")
        print()

    def check_winner(self, player):
        """Checks rows, columns, and diagonals for 3 matching symbols."""
        # Check rows and columns
        for i in range(3):
            if all(self.board[i][j] == player for j in range(3)): return True
            if all(self.board[j][i] == player for j in range(3)): return True
        # Check diagonals
        if self.board[0][0] == player and self.board[1][1] == player and self.board[2][2] == player: return True
        if self.board[0][2] == player and self.board[1][1] == player and self.board[2][0] == player: return True
        return False

    def is_board_full(self):
        """9 & 10. Checks whether the board is completely filled."""
        return all(cell != ' ' for row in self.board for cell in row)

    def get_empty_positions(self):
        """Helper to find all vacant board coordinates."""
        return [(r, c) for r in range(3) for c in range(3) if self.board[r][c] == ' ']

    def start_game(self):
        print("Welcome to Tic-Tac-Toe!")
        self.display_board()

        # 12. The human and computer continue playing alternately...
        while True:
            # 3. The human player selects an empty position and places X in it.
            while True:
                try:
                    move = input("Enter your move (row and column 0-2, separated by space): ")
                    r, c = map(int, move.split())
                    if 0 <= r <= 2 and 0 <= c <= 2 and self.board[r][c] == ' ':
                        self.board[r][c] = self.human
                        break
                    print("That position is taken or invalid! Try again.")
                except (ValueError, IndexError):
                    print("Invalid input format. Please enter two numbers between 0 and 2.")

            print("\nHuman Player's Move:")
            self.display_board()

            # 4. The game checks whether the human player has three X's.
            if self.check_winner(self.human):
                # 5. If the human player wins, display message and end.
                print("Human Player Wins")
                break

            # 9 & 10. Check if draw right after human's move
            if self.is_board_full():
                print("Game Draw")
                break

            # 6. If human does not win, the computer plays its move in an empty position.
            print("Computer is thinking...")
            empty_spots = self.get_empty_positions()
            comp_r, comp_c = random.choice(empty_spots)
            self.board[comp_r][comp_c] = self.computer

            print(f"Computer Player's Move (Row {comp_r}, Col {comp_c}):")
            self.display_board()

            # 7. The game checks whether the computer has three O's.
            if self.check_winner(self.computer):
                # 8. If the computer wins, display message and end.
                print("Computer Player Wins")
                break

            # 9 & 10. If no player has won, check whether the board is completely filled.
            if self.is_board_full():
                print("Game Draw")
                break

            # 11. If empty positions are still available, continue with human's turn.
            print("--- Next Round ---")

if __name__ == "__main__":
    game = TicTacToe()
    game.start_game()