# -*- coding: utf-8 -*-
"""VC.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gdYayLcV0kRi1KlvJV6ts_IL1lZlc-Oa
"""

import random

def vacuum_cleaner_ai(n_rooms):
    # Step 1: Initialize n rooms with random status: 1 for Dirty, 0 for Clean
    # Example for 5 rooms: {0: 1, 1: 0, 2: 1, 3: 1, 4: 0}
    rooms = {i: random.choice([0, 1]) for i in range(n_rooms)}

    print("--- Initial Room States ---")
    for room, status in rooms.items():
        state = "Dirty" if status == 1 else "Clean"
        print(f"Room {room}: {state}")
    print("-" * 30)

    cost = 0  # Track performance cost (moves/actions made)

    # Step 2: Traverse through each room from 0 to n-1
    for current_room in range(n_rooms):
        print(f"\nVacuum entered Room {current_room}")

        # Step 3: Check status and act
        if rooms[current_room] == 1:
            print(f"-> Room {current_room} is DIRTY. Sucking dirt...")
            rooms[current_room] = 0  # Clean the room
            cost += 1
            print(f"-> Room {current_room} is now CLEAN.")
        else:
            print(f"-> Room {current_room} is already CLEAN.")

        # Step 4: Move to the next room if it exists
        if current_room < n_rooms - 1:
            print(f"Moving Right to Room {current_room + 1}...")
            cost += 1

    # Step 5: Final Summary
    print("\n" + "="*30)
    print("All rooms are now CLEAN!")
    print(f"Total actions performed (Cost): {cost}")
    print("="*30)

# Run the program for 5 rooms (Change this number to any 'n' value)
vacuum_cleaner_ai(n_rooms=5)